import Head from "next/head";
import React, { ReactNode } from "react";
import Header from "../header/Header";
import AsideNavigation from "../asideNavigation/asideNavigation";
// import NavigationBar from "../navigationBar/NavigationBar";
// import Footer from "../footer/Footer";
import styles from "./WrapperComponent.module.scss";

type Props = {
  children: ReactNode;
  title: string;
  aside?: boolean;
  footer?: boolean;
  header?: boolean;
};

const WrapperComponent: React.FC<Props> = ({
  children,
  title,
  footer,
  header,
  aside,
}) => {
  return (
    <div>
      <Head>
        {title}
        {/*  <meta name="description" content="Generated by create next app" />*/}
        {/*  <link rel="icon" href="/favicon.ico" />*/}
      </Head>
      {header && <Header />}
      <div className={aside ? styles.mainContent_aside : styles.mainContent}>
        {aside && <AsideNavigation />}
        {children}
      </div>
    </div>
  );
};

export default WrapperComponent;
